version: "3.8"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports: ["8086:8086"]
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=demo-org
      - DOCKER_INFLUXDB_INIT_BUCKET=level_data
    volumes:
      - influx-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports: ["3000:3000"]
    depends_on: [influxdb]
    volumes:
      - grafana-data:/var/lib/grafana
  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    depends_on: [influxdb]
    volumes:
      - ../mock_data:/workspaces/hydro-dashboard-demo/mock_data:ro
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  leaflet:
    build: ../leaflet_app
    ports:
      - "8080:8080"
    volumes:
      - ../leaflet_app:/app
    restart: unless-stopped


volumes:
  influx-data:
  grafana-data:
